### ISSUE TITLE
簡単なblade作成、確認用ルーティングファイルの作成

### ISSUE THREAD

**Issue by hosho624** [nimi1125/blog-app#1]

**Comment by nimi1125** [comment]
20241023＠進捗メモ
layoutsの中に新たに、blogフォルダ追加して、各ページのbladeファイル作製。
トップページ一部コーディング済み

**Comment by nimi1125** [comment]
ワイヤーフレーム
https://www.figma.com/design/zFMnzObdV84JSmGPvddKUP/%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0?node-id=0-1&node-type=canvas&t=eUUjeG52REvyPzie-0
